version: "2.1"
services:

  consumer:
    extends:
      file: docker-compose-base.yml
      service: firebase-consumer
    volumes:
      - ${AETHER_FB_CREDENTIAL_PATH}:/opt/firebase/cert.json
    ports:
      - "${AETHER_FB_EXPOSE_PORT}:${AETHER_FB_EXPOSE_PORT}"
